config/routes.rb
Rails.application.routes.draw do

  resources :photos
  mount RailsAdmin::Engine => '/moana', as: 'rails_admin'
  get 'pages/home'
  get 'pages/contact'
  get 'pages/about'
  get 'pages/service'
  #Quote resources
  resources :quotes, only: [:new, :create]

  root "pages#home"
end

app/models/message.rb
class Message < MailForm::Base
	attribute :firstname
	attribute :surname
	attribute :email
	attribute :phone
	attribute :company
	attribute :location

	attribute :interest
	attribute :services
	attribute :deadline
	attribute :budget
	attribute :company
	attribute :location

	def headers
		{
			:subject => "www.atmospehric.ng: Quotation",
			:to => ENV["email"],
			:from => %("#{firstname}" <#{email}>)
		}
	end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	# VALIDATION
	validates :image, :presence => true
	end

app/models/quote.rb
class Quote
	include ActiveModel::Model
	attr_accessor :fullname, :email, :phone, :date, :type, :guest
	validates :fullname, :email, :phone, :date, :type, :guest, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/atmospheric_pages_controller.rb
class AtmosphericPagesController < ApplicationController
  def home
  end

  def gallery
  end

  def contact
        @quote = Quote.new

  #   @quote = Quote.new(params[:quote])
  #   @quote.request = request
  #   if @quote.deliver
  #     # flash.now[:error] = nil
  #     flash[:notice] = "Thank you for your quote!"
  #     redirect_to root_path
  #   else
  #     flash[:error] = "Cannot send quote."
  #     render :new
  #   end
  end

  def about
  end

  def qoute
  end

  def service
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def contact
        @quote = Quote.new
  end

  def about
  end

  def qoute
  end

  def service
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.order(created_at: :desc).paginate(:page => params[:page], :per_page => 10)
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:image)
    end
  end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def new
  	@quote = Quote.new
  end

  def create
  	@quote = Quote.new(quote_params)

  	if @quote.valid?
      QuoteMailer.message_me(@quote).deliver_now
      redirect_to new_quote_path, notice: "Thank you for your quote."
    else
      flash[:error] = "Cannot send quote."
      render :new
    end
  end

  private

  def quote_params
    params.require(:quote).permit(:fullname, :email, :phone, :date, :type, :guest)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/atmospheric_pages/contact.html.erb
<% provide(:title, 'Contact') %> <!DOCTYPE html>


<div class = "moduler">

	<div class="moduler-image contact-home-image">
	</div>

	<div class = "moduler-head">
		<div class = "row">
			<h1 class = "large-12 columns">
				CONTACT
				<hr>
				<p>
				DESIGN IS OUR PASSION. WITH YOU AS OUR CLIENT, WE WILL AIM FOR ONLY EXCELLENT RESULTS. AN END PRODUCT WORTHY OF YOUR NAME.
				</p>
			</h1>
		</div>

			
		<div class = "row">
			<div class = "large-4 columns address-wrapper">
				<p>Atmospheric Events</p>
				<p>Yaba, Lagos, Nigeria</p>
				<p>+234 80634 72855</p>
				<p>hello@atmospheric.ng</p>
				<a href="https://web.facebook.com/atmosphericevents.com.ng/"><i class = 'fa fa-facebook'></i></a>
				<a href="https://www.instagram.com/atmosphericevents/"><i class = 'fa fa-instagram'></i></a>
			</div>

			<%= link_to "<button>REQUEST A FREE QUOTE</button>".html_safe, new_quote_path, :class => "large-4 columns" %>

		</div>


<!-- <div class = "row">

	<div class = "large-4 columns">
		<img src="">
		<h1></h1>
		<p></p>
		<button></button>
	</div>
	
	<div class = "large-4 columns">
		<img src="">
		<h1></h1>
		<p></p>
		<button></button>
	</div>

	<div class = "large-4 columns">
		<img src="">
		<h1></h1>
		<p></p>
		<button></button>
	</div>

</div> -->


	</div>
</div>

app/views/atmospheric_pages/gallery.html.erb
<% provide(:title, 'Gallery') %> <!DOCTYPE html>

<div class = "moduler">

	<div class="moduler-image gallery-home-image">
	</div>

	<div class = "moduler-head">
		<div class = "row">
			<h1 class = "large-12 columns">
				OUR GALLERY
				<hr>
				<p>Here you can see a sample of projects we have worked on our years of experience to clients around the globe.</p>
			</h1>
		</div>

		<div class = "row gallery-qoute">
			<div class = "moduler-sub-head">

				<!-- <div class = "large-8 columns">
					<a class = "moduler-nav">ALL WORK <span>|</span> WEDDING EVENTS <span>|</span> CORPORATE EVENTS <span>|</span> SOCIAL EVENTS</a>
				</div> -->

				<%= link_to "<button>REQUEST A FREE QUOTE</button>".html_safe, new_quote_path, :class => "large-4 columns" %>

			</div>
		</div>
	</div>

	
	<div class='row gallery-canvas'>
		<section class='large-6 small-12 columns'>
			<%= image_tag("https://s3-us-west-2.amazonaws.com/stutern/atmospheric/DSC_0591-min.jpg") %>
		</section>

		<aside class='large-3 small-12 columns'>
			<%= image_tag("https://s3-us-west-2.amazonaws.com/stutern/atmospheric/DSC_0750-min.jpg") %>
		</aside>

		<aside class='large-3 small-12 columns'>
			<%= image_tag("https://s3-us-west-2.amazonaws.com/stutern/atmospheric/ae_img_two-min.png") %>
		</aside>

		<aside class='large-3 small-12 columns'>
			<%= image_tag("https://s3-us-west-2.amazonaws.com/stutern/atmospheric/ae_img_four-min.png") %>
		</aside>

		<aside class='large-3 small-12 columns'>
			<%= image_tag("https://s3-us-west-2.amazonaws.com/stutern/atmospheric/ae_img_one-min.png") %>
		</aside>
	</div>

	<div class='row gallery-canvas'>

		<section class='large-6 small-12 columns'>
			<%= image_tag("https://s3-us-west-2.amazonaws.com/stutern/atmospheric/DSC_0689-min.jpg") %>
		</section>

		<aside class='large-3 small-12 columns'>
			<%= image_tag("https://s3-us-west-2.amazonaws.com/stutern/atmospheric/DSC_0686-min.jpg") %>
		</aside>

		<aside class='large-3 small-12 columns'>
			<%= image_tag("https://s3-us-west-2.amazonaws.com/stutern/atmospheric/DSC_0676-min.jpg") %>
		</aside>

		<aside class='large-3 small-12 columns'>
			<%= image_tag("https://s3-us-west-2.amazonaws.com/stutern/atmospheric/ae_img_five-min.png") %>
		</aside>

		<aside class='large-3 small-12 columns'>
			<%= image_tag("https://s3-us-west-2.amazonaws.com/stutern/atmospheric/ae_img_three-min.png") %>
		</aside>

	</div>

</div>

app/views/atmospheric_pages/love.html.erb
<% provide(:title, 'Love') %> <!DOCTYPE html>

<h1>Love</h1> <p>
The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a> is a project to make a book and screencasts to teach web development with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
is the sample application for the tutorial.
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <!-- favicon start -->
  <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
  <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
  <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
  <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
  <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
  <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
  <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
  <link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
  <link rel="manifest" href="/manifest.json">
  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
  <meta name="theme-color" content="#ffffff">
  <!-- favicon end -->

  <title>AE | <%= yield(:title) %></title>

  <%= stylesheet_link_tag    "application" %>
  <link href='https://fonts.googleapis.com/css?family=Merriweather:300,300italic,400,400italic,700italic,700,900,900italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<header id="header">
  <div class = "contain-to-grid fixed">
    <nav class="top-bar" data-topbar role="navigation" data-options="sticky_on: large">
      <ul class="title-area">
        <li class="logo">
          <a href="/" title="Atmospheric events : Makes every moment count">
            <%= image_tag("final_logo-min.png",  height: '0', width: '100%', alt: "Atmospheric Events") %>
          </a>
        </li>
        <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>
      <section class="top-bar-section">
        <!-- Right Nav Section -->
        <ul class="right">
          <%= active_link_to 'SERVICE', pages_service_path, :wrap_tag => :li %>
          <%= active_link_to 'GALLERY', photos_path, :wrap_tag => :li %>
          <%= active_link_to 'CONTACT', pages_contact_path, :wrap_tag => :li %>
          <%= active_link_to 'ABOUT', pages_about_path, :wrap_tag => :li %>
          <%= active_link_to 'GET A FREE QUOTE', new_quote_path, :wrap_tag => :li, class: "qouteButton" %>

          <li><a href="https://web.facebook.com/atmosphericevents.com.ng" target="_blank"><i class = 'fa fa-facebook'></i></a></li>
          <li><a href="https://www.instagram.com/atmosphericevents" target="_blank"><i class = 'fa fa-instagram'></i></a></li>
          <li><a href="https://twitter.com/atmosphericevnt" target="_blank"><i class="fa fa-twitter-square"></i></a></li>

        </ul>
      </section>
    </nav>
  </div>
</header>
<body>
  <%# Rails flash messages styled for Zurb Foundation %>
  <% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
  <div data-alert class="alert-box secondary <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
    <%= content_tag :div, msg %>
    <a href="#" class="close">&times;</a>
  </div>
  <% end %>
  <% end %>
  <section id="content">
    <%= yield %>
  </section>
</body>
<footer id="footer">
  <div class="main-footer">
    <div class="row">

      <div class="large-6 small-7 columns">
        <%= image_tag("final_logo_circle-min.png", alt: "Atmospheric Events") %>
        <p><%=Date.today.year%> ATMOSPHERIC EVENTS</p>
      </div>

      <div class="large-6 small-5 columns">
        <a href="https://www.facebook.com/atmosphericevents.com.ng" target="_blank" class="fa fa-facebook-square footer-inline social-links footer-right"></a>
        <a href="https://twitter.com/atmosphericevnt" target="_blank" class="fa fa-twitter-square footer-inline social-links footer-right"></a>
        <a href="https://instagram.com/atmosphericevents" target="_blank" class="fa fa-instagram footer-inline social-links footer-right"></a>
      </div>

    </div>
  </div>
</footer>
</html>

app/views/messages/new.html.erb
<% provide(:title, 'Qoute') %> <!DOCTYPE html>

<%= simple_form_for @message do |f| %>  
  <div class = "qouteWrapper">
	<h1 class = "large-12 columns qoute-title">
		Request a free qoute
	</h1>
	
	<p class = "qoute-title-content">
		Tell us in the following three steps what you're looking for or send an e-mail to <span>info@atmosphericevents.com.</span>
	</p>

	<div class = "qouteWrapper-page-one">
		
		<section class = "qoute-form-wrapper">
			<div class = "row">

			<div class = "qoute-form-title">
			<i class="fa fa-user"></i>
			<p>Step 1. Who are you?</p>
			</div>
				<div class="row">

				    <div class="large-6 columns">
				        <%= f.input :firstname, label: false, placeholder: "Firstname", error: "Firstname is mandatory, please specify one" %>
				    </div>

				    <div class="large-6 columns">
				        <%= f.input :surname, label: false, placeholder: "Surname", error: "Surname is mandatory, please specify one" %>
				    </div>

				</div>

				<div class="row">

				    <div class="large-6 columns">
				        <%= f.input :email, label: false, placeholder: "Email", error: "Email is mandatory, please specify one" %>
				    </div>

				    <div class="large-6 columns">
				        <%= f.input :phone, label: false, placeholder: "Phone", error: "Phone is mandatory, please specify one" %>
				    </div>

				</div>

				<div class="row">

				    <div class="large-6 columns">
				        <%= f.input :company, label: false, placeholder: "Company", error: "Company is mandatory, please specify one" %>
				    </div>

				    <div class="large-6 columns">
				        <%= f.input :location, label: false, placeholder: "Location", error: "Location is mandatory, please specify one" %>
				    </div>

				</div>

				
				<button>NEXT</button>

			</div>
		</section>
	</div>
	
	<div class = "qouteWrapper-page-two">
		
		<section class = "qoute-form-wrapper">
			<div class = "row">

			<div class = "qoute-form-title">
			<i class="fa fa-search"></i>
			<p>Step 2. What are you looking for?</p>
			</div>
					

				<div class="row">

				    <div class="large-6 columns">
					    <div class="large-12 columns">
					        <%= f.input :interest, label: false, placeholder: "What are you interested in?", error: "Please specify one" %>
					    </div>
					    <div class="large-12 columns">
					        <%= f.input :services, label: false, placeholder: "Do you need additional services?", error: "Please specify one" %>
					    </div>
					    <div class="large-12 columns">
					        <%= f.input :deadline, label: false, placeholder: "What is your deadline?", error: "Please specify one" %>
					    </div>
					    <div class="large-12 columns">
					        <%= f.input :budget, label: false, placeholder: "What is your budget?", error: "Please specify one" %>
					    </div>
					    <button><%= link_to "BACK", :back %></button>
				    </div>

				    <div class="large-6 columns">
					    <div class="large-12 columns">
					      <label>Additional information (Brief description of your event)
					        <textarea></textarea>
					      </label>
					    </div>
					    <%= f.button :submit %>
				    </div>

				</div>

				
				

			</div>
		</section>
	</div>

</div>
<% end %>

app/views/pages/about.html.erb
<% provide(:title, 'About Us') %> <!DOCTYPE html>

<div class = "moduler">

	<div class="moduler-image about-home-image">
	</div>

	<div class = "moduler-head">
		<div class = "row">
			<h1 class = "large-12 columns">
				ABOUT US
				<hr>
				<p>
					DESIGN IS OUR PASSION. WITH YOU AS OUR CLIENT, WE WILL AIM FOR ONLY EXCELLENT RESULTS. AN END PRODUCT WORTHY OF YOUR NAME.
				</p>
			</h1>
		</div>

	</div>

</div>


<div class = "row about-content">

	<div class = "large-6 columns">
		<p>
			Atmospheric events, is a dynamic event decorator and planner that produces stunning works for its clients.

			<br/>
			<br/>

			Many extravagant events are in the Atmospheric Events portfolio.

			<br/>
			<br/>

			Together with you, our partner, we look forward to forging a unique event.
		</p>
	</div>


	<%= link_to "<button>REQUEST A FREE QUOTE</button>".html_safe, new_quote_path, :class => "large-6 columns" %>

</div>



<div class = "large-12 columns about-thanks">
	<p>Thanks<br/>for Stopping<br/>by</p>
</div>

app/views/pages/contact.html.erb
<% provide(:title, 'Contact') %> <!DOCTYPE html>
<div class = "moduler">
	<div class="moduler-image contact-home-image">
	</div>
	<div class = "moduler-head">
		<div class = "row">
			<h1 class = "large-12 columns">
				CONTACT
				<hr>
				<p>
					DESIGN IS OUR PASSION. WITH YOU AS OUR CLIENT, WE WILL AIM FOR ONLY EXCELLENT RESULTS. AN END PRODUCT WORTHY OF YOUR NAME.
				</p>
			</h1>
		</div>
		<div class = "row">
			<div class = "large-4 columns address-wrapper">
				<p>Atmospheric Events</p>
				<p>Yaba, Lagos, Nigeria</p>
				<p>+234 80634 72855</p>
				<p>hello@atmospheric.com.ng</p>
				<a href="https://web.facebook.com/atmosphericevents.com.ng/" target="_blank"><i class = 'fa fa-facebook'></i></a>
				<a href="https://www.instagram.com/atmosphericevents/" target="_blank"><i class = 'fa fa-instagram'></i></a>
				<a href="https://twitter.com/atmosphericevnt" target="_blank"><i class="fa fa-twitter-square"></i></a>
			</div>

			<%= link_to "<button>REQUEST A FREE QUOTE</button>".html_safe, new_quote_path, :class => "large-4 columns" %>

		</div>
	</div>
</div>

app/views/pages/home.html.erb
<% provide(:title, 'Home') %> <!DOCTYPE html>
<div class = "home-wrapper">


	<div class="fade">

		<div class="homeImg1">
			<p class = "large-12 columns">
				<i class = "vertical-lineUp"></i>
				<span class = "homeinnerContentTop">We are event decorators and planners</span>
				<span class = "homeinnerContentBottom">DELIGHTFUL</span>
				<i class = "vertical-lineDown"></i>
				<!-- <button class = 'qouteButton'>Tell Us About it</button> -->
				<!-- </p> -->
			</div>

			<div class="homeImg2">
				<p class = "large-12 columns">
					<i class = "vertical-lineUp"></i>
					<span class = "homeinnerContentTop">We are event decorators and planners</span>
					<span class = "homeinnerContentBottom">EVENTFUL</span>
					<i class = "vertical-lineDown"></i>
				</p>
			</div>

			<div class="homeImg3">
				<p class = "large-12 columns">
					<i class = "vertical-lineUp"></i>
					<span class = "homeinnerContentTop">We are event decorators and planners</span>
					<span class = "homeinnerContentBottom">BEAUTIFUL</span>
					<i class = "vertical-lineDown"></i>
				</p>
			</div>

			<div class="homeImg4">
				<p class = "large-12 columns">
					<i class = "vertical-lineUp"></i>
					<span class = "homeinnerContentTop">We are event decorators and planners</span>
					<span class = "homeinnerContentBottom">COLOURFUL</span>
					<i class = "vertical-lineDown"></i>
				</p>
			</div>

		</div>

	</div>

app/views/pages/service.html.erb
<% provide(:title, 'Service') %> <!DOCTYPE html>

<div class = "moduler">
	<div class="moduler-image service-home-image">
	</div>
	<div class = "moduler-head">
		<div class = "row">
			<h1 class = "large-12 columns">
				SERVICE
			</h1>
		</div>
	</div>
</div>

<div class = "row service-content">
	<div class = "large-4 columns">
		<div class = "service-image service-img-one"></div>
		<h3>EVENT PLANNING</h3>
		<hr>
		<p>
			Need and event planner for your next event or wedding? We can do it all. We can determine the what, when, who and how  successful your event will be. We relief you of the headache and leave you to enjoy the celebration.
		</p>
	</div>
	<div class = "large-4 columns">
		<div class = "service-image service-img-two"></div>
		<h3>EVENT COORDINATION </h3>
		<hr>
		<p>
			We stay focused and organized, ensuring that all the details planned are executed. Our vendors show up on time and perform appropriately to wow our guests.
		</p>
	</div>
	<div class = "large-4 columns">
		<div class = "service-image service-img-three"></div>
		<h3>EVENT DESIGN</h3>
		<hr>
		<p>
			We have a team of event decorators and designers. We take our design seriously, with creativity and detailed symmetry. Our work stands out and we exceed all our client's expectations. Our gallery says it all.
		</p>
	</div>
	<div class = "service-qoute-small-wrapper">
		<div class = "large-12 columns">
			<div class = "large-4 columns">
				<%= link_to "<button>VIEW OUR PORTFOLIO</button>".html_safe, photos_path, :class => "service-qoute-small" %>
			</div>
			<div class = "large-4 columns">
				<%= link_to "<button>VIEW OUR PORTFOLIO</button>".html_safe, photos_path, :class => "service-qoute-small" %>
			</div>
			<div class = "large-4 columns">
				<%= link_to "<button>VIEW OUR PORTFOLIO</button>".html_safe, photos_path, :class => "service-qoute-small" %>
			</div>
		</div>
	</div>
</div>

app/views/photos/_form.html.erb
<%= form_for(@photo) do |f| %>
<% if @photo.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

  <ul>
    <% @photo.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :image %><br>
  <%= f.file_field :image %>
</div>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<% provide(:title, 'Gallery') %> <!DOCTYPE html>

<div class = "moduler">

  <div class="moduler-image gallery-home-image">
  </div>

  <div class = "moduler-head">
    <div class = "row">
      <h1 class = "large-12 columns">
        OUR GALLERY
        <hr>
        <p>Here you can see a sample of projects we have worked on our years of experience to clients around the globe.</p>
      </h1>
    </div>

    <div class = "row gallery-qoute">
      <div class = "moduler-sub-head">

        <%= link_to "<button>REQUEST A FREE QUOTE</button>".html_safe, new_quote_path, :class => "large-4 columns" %>

      </div>
    </div>
  </div>


  <div class='row gallery-canvas'>
    <% @photos.each do |photo| %>
    <section class='large-6 small-12 columns'>
      <%= image_tag(photo.image_url(:large)) %>
    </section>
    <% end %>
  </div>
  <br>
  <div class='row gallery-canvas apple_pagination'>
    <%= will_paginate @photos, :page_links => false %>
  </div>
  <br><br><br>

</div>

app/views/photos/new.html.erb
<form>
  <div class="row">
    <h1>New Photo</h1>

    <%= render 'form' %>

    <%= link_to 'Back', photos_path %>
  </div>
</form>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @photo.image %>
</p>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>

app/views/quotes/new.html.erb
<% provide(:title, 'Qoute') %> <!DOCTYPE html>

<%= simple_form_for @quote do |f| %>
<div class = "qouteWrapper">
	<h1 class = "large-12 columns qoute-title">
		Request a free quote
	</h1>

	<p class = "qoute-title-content">
		Tell us in the following steps what you're looking for or send an e-mail to <span>hello@atmospheric.com.ng</span>
	</p>


	<section class = "qoute-form-wrapper">
		<div class = "row">
			<div class = "qoute-form-innerwrapper">

				<div class = "qoute-form-title">
					<i class="fa fa-user"></i>
					<p>We would love to hear from you.</p>
				</div>


				<div class="large-6 small-12 columns">
					<%= f.input :fullname, label: false, placeholder: "Fullname", error: "Name is mandatory, please specify one" %>
				</div>


				<div class="large-6 small-12 columns">
					<%= f.input :email, label: false, placeholder: "Email", error: "Email is mandatory, please specify one" %>
				</div>


				<div class="large-6 small-12 columns">
					<%= f.input :phone, label: false, placeholder: "Phone", error: "Phone is mandatory, please specify one" %>
				</div>

				<div class="large-6 small-12 columns">
					<%= f.input :date, label: false, placeholder: "Event Date", error: "Phone is mandatory, please specify one" %>
				</div>

				<div class="large-6 small-12 columns">
					<%= f.input :type, label: false, placeholder: "Type of Event", error: "Phone is mandatory, please specify one" %>
				</div>

				<div class="large-6 small-12 columns">
					<%= f.input :guest, label: false, placeholder: "Number of Guests", error: "Phone is mandatory, please specify one" %>
				</div>


				<%= f.button :submit %>

			</div	>
		</div	>
	</section>
</div>
<% end %>